### ISSUE TITLE
Window result misplaced on your tool (Correct Geometry - Resolution Calculator v2.0)

### ISSUE THREAD

**Issue by Hyllian** [Dogway/emulation-random#7]
Hi,

I'd like to use your tool called "Correct Geometry - Resolution Calculator v2.0", but my system is only 1366x768 and when I provide the inputs and click the OK button, the result window shows up partially outside my viewing screen, like in the screenshot below. Could you centralize the result window so that I can see the results?

![results-offscreen](https://user-images.githubusercontent.com/825708/97104985-bb681c80-1696-11eb-87c6-58078f79ff8b.png)

**Comment by Dogway** [comment]
Sorry for the delay, didn't notice the issue ticket.
Try now to see if it's fixed.

**Comment by Dogway** [comment]
Closing, open back if issue persists
